openapi: 3.0.0
paths:
  /cities/{id}:
    get:
      operationId: findById
      summary: 市区町村IDの市区町村情報を取得する
      description: 市区町村IDの市区町村情報を取得する
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
      tags:
        - cities
info:
  title: Cities
  description: Cities API description
  version: '1.0'
  contact: {}
tags:
  - name: cities
    description: ''
servers: []
components:
  schemas:
    City:
      type: object
      properties:
        id:
          type: number
          example: 27100
          description: 市区町村ID
        m_prefecture_id:
          type: number
          example: 27
          description: 市区町村に紐づく都道府県ID
        name:
          type: string
          example: 大阪市
          description: 市区町村名
        name_hiragana:
          type: string
          example: おおさかし
          description: 市区町村名_ひらがな
        name_katakana:
          type: string
          example: オオサカシ
          description: 市区町村名_カタカナ
        parent_city_id:
          type: number
          nullable: true
          example: 27100
          description: 特別区,行政区が属する政令指定都市の市区町村ID
        is_designated:
          type: boolean
          example: true
          description: 政令指定都市フラグ
      required:
        - id
        - m_prefecture_id
        - name
        - name_hiragana
        - name_katakana
        - parent_city_id
        - is_designated
